<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.17763.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>StreamFlow.Plugin.SDK</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StreamFlow.Core\StreamFlow.Core.csproj" />
  </ItemGroup>
</Project>
