using StreamFlow.App.ViewModels.Pages;

namespace StreamFlow.App.Tests;

public class AudioViewModelTests
{
    [Fact]
    public void IncrementCommand_Increments_Counter()
    {
        var vm = new AudioViewModel();

        Assert.Equal(0, vm.Count);

        // Generated by [RelayCommand]; invoke via reflection to avoid toolkit dependency
        var cmd = vm.GetType().GetProperty("IncrementCounterCommand")!.GetValue(vm)!;
        cmd.GetType().GetMethod("Execute")!.Invoke(cmd, new object?[] { null });

        Assert.Equal(1, vm.Count);
    }
}
