<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<TargetFramework>net9.0-windows10.0.17763.0</TargetFramework>
    <UseWPF>false</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\StreamFlow.App\StreamFlow.App.csproj" />
    <ProjectReference Include="..\StreamFlow.Core\StreamFlow.Core.csproj" />
    <ProjectReference Include="..\StreamFlow.Plugin.SDK\StreamFlow.Plugin.SDK.csproj" />
    <ProjectReference Include="..\plugins\StreamFlow.Plugin.Marquee\StreamFlow.Plugin.Marquee.csproj" />
  </ItemGroup>
</Project>
